In [10]:
import numpy as np 
from fractions import Fraction # so that numbers are not displayed in decimal.

print("\n                 ****SiMplex Algorithm ****\n\n")

# inputs 

# A will contain the coefficients of the constraints
A = np.array([  [0,0,0,0,1,1],
                [0,1,0,0,0,1],
                [0,0,1,1,1,0],
                [1,1,0,1,0,0]])
# [[1, 1, 0, 1], [2, 1, 1, 0]])
# b will contain the amount of resources 
b = np.array([3, 5, 4, 7])           
# c will contain coefficients of objective function Z      
c = np.array([1, 1, 1, 1,1,1])             

# B will contain the basic variables that make identity matrix
cb = np.array(c[3])
B = np.array([[3], [2]])    


 # cb contains their corresponding coefficients in Z   
cb = np.vstack((cb, c[2]))        
xb = np.transpose([b])                 
# combine matrices B and cb
table = np.hstack((B, cb))  

print(table)
print(xb)
table = np.hstack((table, xb))         
# combine matrices B, cb and xb
# finally combine matrix A to form the complete simplex table
table = np.hstack((table, A))         
# change the type of table to float
table = np.array(table, dtype ='float') 
# inputs end

# if min problem, make this var 1
MIN = 1

print("Table at itr = 0")
print("B \tCB \tXB \ty1 \ty2 \ty3 \ty4")
for row in table:
    for el in row:
                # limit the denominator under 100
        print(Fraction(str(el)).limit_denominator(100), end ='\t') 
    print()
print()
print("Simplex Working....")

# when optimality reached it will be made 1
reached = 0     
itr = 1
unbounded = 0
alternate = 0

while reached == 0:

    print("Iteration: ", end =' ')
    print(itr)
    print("B \tCB \tXB \ty1 \ty2 \ty3 \ty4")
    for row in table:
        for el in row:
            print(Fraction(str(el)).limit_denominator(100), end ='\t')
        print()

    # calculate Relative profits-> cj - zj for non-basics
    i = 0
    rel_prof = []
    while i<len(A[0]):
        rel_prof.append(c[i] - np.sum(table[:, 1]*table[:, 3 + i]))
        i = i + 1

    print("rel profit: ", end =" ")
    for profit in rel_prof:
        print(Fraction(str(profit)).limit_denominator(100), end =", ")
    print()
    i = 0
    
    b_var = table[:, 0]
    # checking for alternate solution
    while i<len(A[0]):
        j = 0
        present = 0
        while j<len(b_var):
            if int(b_var[j]) == i:
                present = 1
                break;
            j+= 1
        if present == 0:
            if rel_prof[i] == 0:
                alternate = 1
                print("Case of Alternate found")
                # print(i, end =" ")
        i+= 1
    print()
    flag = 0
    for profit in rel_prof:
        if profit>0:
            flag = 1
            break
        # if all relative profits <= 0
    if flag == 0:
        print("All profits are <= 0, optimality reached")
        reached = 1
        break

    # kth var will enter the basis
    k = rel_prof.index(max(rel_prof))
    min = 99999
    i = 0;
    r = -1
    # min ratio test (only positive values)
    while i<len(table):
        if (table[:, 2][i]>0 and table[:, 3 + k][i]>0): 
            val = table[:, 2][i]/table[:, 3 + k][i]
            if val<min:
                min = val
                r = i     # leaving variable
        i+= 1

        # if no min ratio test was performed
    if r ==-1:
        unbounded = 1
        print("Case of Unbounded")
        break

    print("pivot element index:", end =' ')
    print(np.array([r, 3 + k]))

    pivot = table[r][3 + k]
    print("pivot element: ", end =" ")
    print(Fraction(pivot).limit_denominator(100))
        
        # perform row operations
    # divide the pivot row with the pivot element
    table[r, 2:len(table[0])] = table[
            r, 2:len(table[0])] / pivot
            
    # do row operation on other rows
    i = 0
    while i<len(table):
        if i != r:
            table[i, 2:len(table[0])] = table[i, 2:len(table[0])] - table[i][3 + k] * table[r, 2:len(table[0])]
        i += 1

    
    # assign the new basic variable
    table[r][0] = k
    table[r][1] = c[k]
    
    print()
    print()
    itr+= 1
    

print()

print("***************************************************************")
if unbounded == 1:
    print("UNBOUNDED LPP")
    exit()
if alternate == 1:
    print("ALTERNATE Solution")

print("optimal table:")
print("B \tCB \tXB \ty1 \ty2 \ty3 \ty4")
for row in table:
    for el in row:
        print(Fraction(str(el)).limit_denominator(100), end ='\t')
    print()
print()
print("value of Z at optimality: ", end =" ")

basis = []
i = 0
sum = 0
while i<len(table):
    sum += c[int(table[i][0])]*table[i][2]
    temp = "x"+str(int(table[i][0])+1)
    basis.append(temp)
    i+= 1
# if MIN problem make z negative
if MIN == 1:
    print(-Fraction(str(sum)).limit_denominator(100))
else:
    print(Fraction(str(sum)).limit_denominator(100))
print("Final Basis: ", end =" ")
print(basis)

print("Simplex Finished...")
print()


                 ****SiMplex Algorithm ****


[[3 1]
 [2 1]]
[[3]
 [5]
 [4]
 [7]]


ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 4

In [14]:
np.transpose([[0., 0., 0., 1.],
       [0., 1., 0., 1.],
       [0., 0., 1., 0.],
       [0., 0., 1., 1.],
       [1., 0., 1., 0.],
       [1., 1., 0., 0.]])

array([[0., 0., 0., 0., 1., 1.],
       [0., 1., 0., 0., 0., 1.],
       [0., 0., 1., 1., 1., 0.],
       [1., 1., 0., 1., 0., 0.]])

In [17]:
import numpy as np
from scipy.optimize import linprog


# Coef matrix
A = np.array([[0., 0., 0., 0., 1., 1.],
       [0., 1., 0., 0., 0., 1.],
       [0., 0., 1., 1., 1., 0.],
       [1., 1., 0., 1., 0., 0.]])

# expected values
b = np.array([3, 5, 4, 7])

# success function
c = np.array([1,1,1,1,1,1])

res = linprog(
    c, 
    A_ub=A, 
    b_ub=b,
    bounds=(0, None), method='simplex')
print('Optimal value:', res.fun, '\nX:', res.x) 

Optimal value: 0.0 
X: [0. 0. 0. 0. 0. 0.]


/var/folders/s9/7fk00zsd7tvbh1nf7nkckk840000gn/T/ipykernel_7251/3287128403.py:17: DeprecationWarning: `method='simplex'` is deprecated and will be removed in SciPy 1.11.0. Please use one of the HiGHS solvers (e.g. `method='highs'`) in new code.
  res = linprog(c, A_ub=A, b_ub=b,bounds=(0, None), method='simplex')


In [27]:
# Coef matrix
A = np.array([
    [0., 0., 0., 0., 1., 1.],
    [0., 1., 0., 0., 0., 1.],
    [0., 0., 1., 1., 1., 0.],
    [1., 1., 0., 1., 0., 0.]
])

# expected values
b = np.array([-3, -5, -4, -7])

# success function
c = np.array([1,1,1,1,1,1])


linprog(
    c, 
    A_ub=A, 
    b_ub=b,
    method="simplex", 
    bounds=(0, None))

/var/folders/s9/7fk00zsd7tvbh1nf7nkckk840000gn/T/ipykernel_7251/2562299798.py:16: DeprecationWarning: `method='simplex'` is deprecated and will be removed in SciPy 1.11.0. Please use one of the HiGHS solvers (e.g. `method='highs'`) in new code.
  linprog(


 message: Phase 1 of the simplex method failed to find a feasible solution. The pseudo-objective function evaluates to 1.9e+01 which exceeds the required tolerance of 1e-09 for a solution to be considered 'close enough' to zero to be a basic solution. Consider increasing the tolerance to be greater than 1.9e+01. If this tolerance is unacceptably  large the problem may be infeasible.
 success: False
  status: 2
     fun: 0.0
       x: [ 0.000e+00  0.000e+00  0.000e+00  0.000e+00  0.000e+00
            0.000e+00]
     nit: 0

In [38]:
obj = [1, 1, 1]

lhs_ineq = np.array([

    [0,1,0,],
    [1,0,1]

    # [0., 0., 0., 0., 1., 1.],
    # [0., 1., 0., 0., 0., 1.],
    # [0., 0., 1., 1., 1., 0.],
    # [1., 1., 0., 1., 0., 0.]
])

rhs_ineq = [ 2,  # Manpower
             3,  # Material A
             
             ]  # Material B

opt = linprog(c=obj, A_ub=lhs_ineq, b_ub=rhs_ineq, method="revised simplex")

display(opt)
print(np.round(opt.x,3))

#      con: array([], dtype=float64)
#      fun: -1900.0
#  message: 'Optimization terminated successfully.'
#      nit: 2
#    slack: array([ 0., 40.,  0.])
#   status: 0
#  success: True
#        x: array([ 5.,  0., 45.,  0.])

/var/folders/s9/7fk00zsd7tvbh1nf7nkckk840000gn/T/ipykernel_7251/3999323091.py:19: DeprecationWarning: `method='revised simplex'` is deprecated and will be removed in SciPy 1.11.0. Please use one of the HiGHS solvers (e.g. `method='highs'`) in new code.
  opt = linprog(c=obj, A_ub=lhs_ineq, b_ub=rhs_ineq, method="revised simplex")


 message: Optimization terminated successfully.
 success: True
  status: 0
     fun: 0.0
       x: [ 0.000e+00  0.000e+00  0.000e+00]
     nit: 0

[0. 0. 0.]


In [40]:
!pip install pulp

Defaulting to user installation because normal site-packages is not writeable
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.4/16.4 MB 10.2 MB/s eta 0:00:0000:0100:01

[notice] A new release of pip is available: 24.1.1 -> 25.3
[notice] To update, run: /Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip


In [43]:
from pulp import LpMaximize,LpMinimize, LpProblem, LpStatus, lpSum, LpVariable

In [52]:
model = LpProblem(name="small-problem", sense=LpMinimize)

A = LpVariable(name='A', lowBound=0)
B = LpVariable(name='B', lowBound=0)
C = LpVariable(name='C', lowBound=0)
# A = LpVariable(name='A', lowBound=0)

model += (1*A + 0*B + 0*C == 3, 'first')
model += (0*A + 1*B + 1*C == 2, 'second')


# For larger problems, it’s often more convenient to use lpSum() with a list or other sequence than to repeat 
# the + operator. For example, you could add the objective function to the model with this statement:

# Add the objective function to the model
model += lpSum([A, B, C])


model

# status = model.solve()

small-problem:
MINIMIZE
1*A + 1*B + 1*C + 0.0
SUBJECT TO
first: A = 3

second: B + C = 2

VARIABLES
A Continuous
B Continuous
C Continuous

In [49]:
model.variables()

[A, B, C]

In [68]:
model = LpProblem(name="small-problem", sense=LpMinimize)
matrix = [
    [0., 0., 0., 0., 1., 1.],
    [0., 1., 0., 0., 0., 1.],
    [0., 0., 1., 1., 1., 0.],
    [1., 1., 0., 1., 0., 0.]]

target = [3, 5, 4, 7]
x = {i: LpVariable(name=f"x{i}", lowBound=0) for i in range(0, len(matrix[0]))}


for i,row in enumerate(matrix):
    expr = lpSum([ x[j] * v for j, v in enumerate(row)])==target[i]
    print(expr)
    model += (expr, 'Expr_'+str(i))


# target function
model += lpSum(x)




model.solve()


# Get the results
print(f"status: {model.status}, {LpStatus[model.status]}")
print(f"objective: {model.objective.value()}")
print("optimum:", [v.value() for v in x.values()])
# for var in x.values():
#     print(f"{var.name}: {var.value()}")

# for name, constraint in model.constraints.items():
#     print(f"{name}: {constraint.value()}")


x4 + x5 = 3.0
x1 + x5 = 5.0
x2 + x3 + x4 = 4.0
x0 + x1 + x3 = 7.0
Welcome to the CBC MILP Solver 
Version: 2.10.3 
Build Date: Dec 15 2019 

command line - /Users/eriksklotins/Library/Python/3.9/lib/python/site-packages/pulp/apis/../solverdir/cbc/osx/i64/cbc /var/folders/s9/7fk00zsd7tvbh1nf7nkckk840000gn/T/de2997856b9044b4a0846edcede12439-pulp.mps -timeMode elapsed -branch -printingOptions all -solution /var/folders/s9/7fk00zsd7tvbh1nf7nkckk840000gn/T/de2997856b9044b4a0846edcede12439-pulp.sol (default strategy 1)
At line 2 NAME          MODEL
At line 3 ROWS
At line 9 COLUMNS
At line 26 RHS
At line 31 BOUNDS
At line 32 ENDATA
Problem MODEL has 4 rows, 6 columns and 10 elements
Coin0008I MODEL read with 0 errors
Option for timeMode changed from cpu to elapsed
Presolve 2 (-2) rows, 4 (-2) columns and 6 (-4) elements
Perturbing problem by 0.001% of 1 - largest nonzero change 3.994764e-05 ( 0.003994764%) - largest zero change 0
0  Obj 5.0000587 Primal inf 8.999998 (2)
2  Obj 10.000188
Optim