In [23]:

# file_path = 'test_input.txt'
file_path = 'input.txt'
with open(file_path) as file:
    lines =  [[k.strip(', ') for k in line.rstrip().split(' ')] for line in file]


# print(lines)
data = [np.array([int(a[2]), int(a[4]), int(a[6]), int(a[8]), int(a[10]) ]) for a in lines]

ingredients = [a[0] for a in lines]

display(data)
display(ingredients)
# lines

[array([ 4, -2,  0,  0,  5]),
 array([ 0,  5, -1,  0,  8]),
 array([-1,  0,  5,  0,  6]),
 array([ 0,  0, -2,  2,  1])]

['Frosting:', 'Candy:', 'Butterscotch:', 'Sugar:']

In [127]:
import numpy as np
# must add up 100
amounts = [30,25,25,20]

def calculate(ingredients, amounts):

    result = []

    for i, ingredient in enumerate(ingredients):
        result.append(ingredient * amounts[i])

    return [ max(0, sum(a))  for a in np.transpose(result)]

t = calculate(data, amounts)
display(t[:-1])
print('answer is = ', prod(t[:-1]))



[95, 65, 60, 40]

answer is =  14820000


In [145]:
# Butterscotch: capacity -1, durability -2, flavor 6, texture 3, calories 8
# Cinnamon: capacity 2, durability 3, flavor -2, texture -1, calories 3

from math import prod
test = np.array([[-1, -2,6,3,8], [2, 3,-2,-1,3]])
t = calculate(test, [40, 60])

display(t)
print('answer is = ', prod(t[:-1]))


[80, 100, 120, 60, 500]

answer is =  57600000




        array([ 4 A, -2 A,  0 A,  0 A]),
        array([ 0 B,  5 B, -1 B,  0 B]),
        array([-1 C,  0 C,  5 C,  0 C]),
        array([ 0 D,  0 D, -2 D,  2 D])


         4 A            - 1 C       = v1
        -2 A +   5 B                = v2
                -1 B    + 5 C - 2 D = v3
                                2 D = v4
        --------------------------------

        


        where:

        A + B +C +D = 100
        maximize:

        prod([v1,v2,v3,v4])




In [ ]:

R = 10
for A in range(100):
    # print(f'A = {A}, iterating B between {10-A} - {10+1}')
    for B in range(R-A, R+1-A):
        for C
        print(A, B, A+B)


0 10 10
1 9 10
2 8 10
3 7 10
4 6 10
5 5 10
6 4 10
7 3 10
8 2 10
9 1 10


In [136]:
from itertools import permutations

buf = []
for v in (permutations(range(1, 100), 4 )):
    if sum(v) == 100:
        buf.append(v)

# Part I

In [146]:
result = 0
opt = None
for i, v in enumerate(buf):
    # if i % 100 == 0:
        # print(i, result)
    t = calculate(data, v)
    r = prod(t[:-1])
    if (r>result):
        result = r
        opt = v
    


print(result, opt)



# 184338000 too much
# 18965440

18965440 (24, 29, 31, 16)


# Part II

In [147]:
result = 0
opt = None
for i, v in enumerate(buf):
    # if i % 100 == 0:
        # print(i, result)
    t = calculate(data, v)
    r = prod(t[:-1])
    if (r>result) and (t[-1] == 500):
        result = r
        opt = v
    


print(result, opt)




15862900 (21, 23, 31, 25)
